
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import {SessionProvider} from "@/context/SessionProvider";
export const metadata: Metadata = {
  title: 'Uber Eats',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <SessionProvider>
              {children}
          </SessionProvider>
      </body>
    </html>
  )
}
